image: registry.csc.sibsutis.ru/ci/git-clang-format:latest

stages:
  - check-format
  - build

check-format:
  stage: check-format
  script:
  - find . -type f -name '*.[ch]' ! -name 'ctest.h' | xargs clang-format --style GNU -i --verbose
  - git diff --exit-code

build:
  stage: build
  script:
    - make && make test
